export const tags = [{
    icon: require('@/assets/images/tag-1.png'),
    price: 100,
    desc: '这是描述,这是1折描述',
    ischeck: false,
    id: 1
}, {
    icon: require('@/assets/images/tag-2.png'),
    price: 50,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 2
}, {
    icon: require('@/assets/images/tag-3.png'),
    price: 150,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 3
}, {
    icon: require('@/assets/images/tag-4.png'),
    price: 100,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 4
}, {
    icon: require('@/assets/images/tag-5.png'),
    price: 50,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 5
}, {
    icon: require('@/assets/images/tag-6.png'),
    price: 150,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 6
}, {
    icon: require('@/assets/images/tag-7.png'),
    price: 100,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 7
}, {
    icon: require('@/assets/images/tag-8.png'),
    price: 50,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 8
}, {
    icon: require('@/assets/images/tag-9.png'),
    price: 150,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 9
}, {
    icon: require('@/assets/images/tag-10.png'),
    price: 100,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 10
}, {
    icon: require('@/assets/images/tag-11.png'),
    price: 50,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 11
}, {
    icon: require('@/assets/images/tag-12.png'),
    price: 150,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 12
}, {
    icon: require('@/assets/images/tag-13.png'),
    price: 100,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 13
}, {
    icon: require('@/assets/images/tag-14.png'),
    price: 50,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 14
}, {
    icon: require('@/assets/images/tag-15.png'),
    price: 150,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 15
}, {
    icon: require('@/assets/images/tag-16.png'),
    price: 100,
    desc: '这是描述,这是描述',
    ischeck: false,
    id: 16
}, {
    icon: require('@/assets/images/tag-17.png'),
    desc: '看房退,这是描述',
    price: 50,
    ischeck: false,
    id: 17
}, {
    icon: require('@/assets/images/tag-18.png'),
    desc: '成交退半是指只要成交就退还50%的信息费，该标签可吸引更多客户看房。',
    price: 150,
    ischeck: false,
    id: 18
}, {
    icon: require('@/assets/images/tag-19.png'),
    desc: '看房全退是指只要来看房就退还100%的信息费，该标签可吸引更多客户看房。',
    price: 50,
    ischeck: false,
    id: 19
}]
